# Generated by Django 5.2.1 on 2025-05-13 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zakladatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno zakladatele musí být vyplněno'}, help_text='Zadejte jméno zakladatele', max_length=60, verbose_name='Jméno zakladatele')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení zakladatele musí být vyplněno'}, help_text='Zadejte příjmení zakladatele', max_length=50, verbose_name='Příjmení zakladatele')),
                ('narozeni', models.DateField(error_messages={'blank': 'Datum narození zakladatele musí být vyplněno'}, help_text='YYYY-MM-DD', verbose_name='Datum narození')),
                ('narodnost', models.CharField(error_messages={'blank': 'Národnost zakladatele musí být vyplněna'}, help_text='Zadejte národnost zakladatele', max_length=60, verbose_name='Národnost')),
                ('biografie', models.TextField(blank=True, verbose_name='Životopis')),
                ('fotografie', models.ImageField(upload_to='zakladatele/', verbose_name='Fotografie autora')),
            ],
            options={
                'verbose_name': 'Zakladatel',
                'verbose_name_plural': 'Zakladatelé',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Znacka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název značky musí být vyplněn'}, help_text='Zadejte název značky', max_length=40, verbose_name='Název značky')),
                ('zeme', models.CharField(error_messages={'blank': 'Země musí být vyplněna'}, help_text='Zadejte zemi', max_length=60, verbose_name='Země')),
                ('rok_zalozeni', models.PositiveIntegerField(help_text='Zadejte rok založení značky (1500-2100)', validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok založení')),
            ],
            options={
                'verbose_name': 'Značka',
                'verbose_name_plural': 'Značky',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název modelu musí být vyplněn'}, help_text='Zadejte název modelu', max_length=60, verbose_name='Název modelu')),
                ('rok_zalozeni', models.DateField(error_messages={'blank': 'Rok založení modelu musí být vyplněn'}, help_text='Zadejte rok založení modelu', verbose_name='Rok založení')),
                ('typ', models.CharField(error_messages={'blank': 'Typ modelu musí být vyplněn'}, help_text='Zadejte typ modelu', max_length=60, verbose_name='Typ')),
                ('fotografie', models.ImageField(error_messages={'blank': 'Fotografie modelu musí být vybrána'}, help_text='Vyberte fotografii modelu', upload_to='modely/', verbose_name='Fotografie modelu')),
                ('znacka', models.ForeignKey(error_messages={'blank': 'Značka musí být vybrána'}, help_text='Vyberte značku', on_delete=django.db.models.deletion.CASCADE, to='auta.znacka', verbose_name='Značka')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modely',
                'ordering': ['nazev'],
            },
        ),
    ]
