# Generated by Django 5.2.1 on 2025-05-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='znacka',
            name='popis',
            field=models.TextField(blank=True, help_text='Zadejte popis značky', verbose_name='Popis značky'),
        ),
        migrations.AlterField(
            model_name='zakladatel',
            name='biografie',
            field=models.TextField(blank=True, help_text='Zadejte životopis zakladatele', verbose_name='Životopis'),
        ),
        migrations.AlterField(
            model_name='znacka',
            name='zeme',
            field=models.CharField(error_messages={'blank': 'Země musí být vyplněna'}, help_text='Zadejte zemi vzniku', max_length=60, verbose_name='Země'),
        ),
    ]
