# Generated by Django 5.2.1 on 2025-05-13 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0002_znacka_popis_alter_zakladatel_biografie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='rok_zalozeni',
            field=models.PositiveIntegerField(error_messages={'blank': 'Rok založení modelu musí být vyplněn'}, help_text='Zadejte rok vzniku modelu (1500-2100)', validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok založení'),
        ),
        migrations.AlterField(
            model_name='znacka',
            name='rok_zalozeni',
            field=models.PositiveIntegerField(error_messages={'blank': 'Rok založení značky musí být vyplněn'}, help_text='Zadejte rok založení značky (1500-2100)', validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok založení'),
        ),
    ]
