# Generated by Django 5.2.1 on 2025-05-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0003_alter_model_rok_zalozeni_alter_znacka_rok_zalozeni'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakladatel',
            name='znacka',
            field=models.ForeignKey(blank=True, default=1, help_text='Vyberte značku', null=True, on_delete=django.db.models.deletion.CASCADE, to='auta.znacka', verbose_name='Značka'),
        ),
    ]
