# Generated by Django 5.2.1 on 2025-05-13 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0004_zakladatel_znacka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakladatel',
            name='znacka',
            field=models.ForeignKey(default=1, error_messages={'blank': 'Značka musí být vybrána'}, help_text='Vyberte značku', null=True, on_delete=django.db.models.deletion.CASCADE, to='auta.znacka', verbose_name='Značka'),
        ),
    ]
