# Generated by Django 5.2.1 on 2025-05-14 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0006_alter_model_znacka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název modelu musí být vyplněn'}, help_text='Zadejte název modelu', max_length=60, verbose_name='Název modelu')),
                ('rok_zalozeni', models.PositiveIntegerField(error_messages={'blank': 'Rok založení modelu musí být vyplněn'}, help_text='Zadejte rok vzniku modelu (1500-2100)', validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok založení')),
                ('typ', models.CharField(error_messages={'blank': 'Typ modelu musí být vyplněn'}, help_text='Zadejte typ modelu', max_length=60, verbose_name='Typ')),
                ('fotografie', models.ImageField(error_messages={'blank': 'Fotografie modelu musí být vybrána'}, help_text='Vyberte fotografii modelu', upload_to='modely/', verbose_name='Fotografie modelu')),
                ('znacka', models.ForeignKey(error_messages={'blank': 'Značka musí být vybrána'}, help_text='Vyberte značku', on_delete=django.db.models.deletion.CASCADE, to='auta.znacka', verbose_name='Značka')),
            ],
            options={
                'verbose_name': 'Druh',
                'verbose_name_plural': 'Druhy',
                'ordering': ['nazev'],
            },
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
