# Generated by Django 5.2.1 on 2025-05-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0007_druh_delete_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druh',
            name='fotografie',
            field=models.ImageField(error_messages={'blank': 'Fotografie modelu musí být vybrána'}, help_text='Vyberte fotografii modelu', upload_to='druhy/', verbose_name='Fotografie modelu'),
        ),
        migrations.AlterField(
            model_name='zakladatel',
            name='narozeni',
            field=models.DateField(error_messages={'blank': 'Datum narození zakladatele musí být vyplněno'}, help_text='Zadejte datum narození zakladatele', verbose_name='Datum narození'),
        ),
    ]
