# Generated by Django 5.2.1 on 2025-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0008_alter_druh_fotografie_alter_zakladatel_narozeni'),
    ]

    operations = [
        migrations.AddField(
            model_name='druh',
            name='popis',
            field=models.TextField(blank=True, help_text='Zadejte popis modelu', verbose_name='Popis modelu'),
        ),
    ]
