# Generated by Django 5.2.1 on 2025-05-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0009_druh_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='znacka',
            name='fotografie',
            field=models.ImageField(blank=True, null=True, upload_to='znacky_loga/', verbose_name='Fotografie autora'),
        ),
    ]
