# Generated by Django 5.2.1 on 2025-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0010_znacka_fotografie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='znacka',
            name='fotografie',
        ),
        migrations.AddField(
            model_name='znacka',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='znacky_loga/', verbose_name='Logo značky'),
        ),
    ]
