# Generated by Django 5.2.1 on 2025-05-15 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0011_remove_znacka_fotografie_znacka_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='znacka',
            name='zakladatel',
            field=models.ForeignKey(blank=True, error_messages={'blank': 'Zakladatel značky musí být vybrán'}, help_text='Vyberte zakladatele značky', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='znacky', to='auta.zakladatel', verbose_name='Zakladatel'),
        ),
        migrations.AlterField(
            model_name='zakladatel',
            name='znacka',
            field=models.ForeignKey(default=1, error_messages={'blank': 'Značka musí být vybrána'}, help_text='Vyberte značku', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zakladatele', to='auta.znacka', verbose_name='Značka'),
        ),
    ]
