# Generated by Django 5.2.1 on 2025-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0012_znacka_zakladatel_alter_zakladatel_znacka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druh',
            name='popis',
            field=models.TextField(help_text='Zadejte popis modelu', verbose_name='Popis modelu'),
        ),
    ]
