# Generated by Django 5.2.1 on 2025-05-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0013_alter_druh_popis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znacka',
            name='popis',
            field=models.TextField(help_text='Zadejte popis značky', verbose_name='Popis značky'),
        ),
    ]
