# Generated by Django 5.2.1 on 2025-05-20 11:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0014_alter_znacka_popis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znacka',
            name='logo',
            field=models.ImageField(default='default/logo.png', error_messages={'blank': 'Logo značky musí být vybráno'}, help_text='Vyberte logo značky', upload_to='znacky_loga/', verbose_name='Logo značky'),
        ),
        migrations.AlterField(
            model_name='znacka',
            name='popis',
            field=models.TextField(error_messages={'blank': 'Popis značky musí být vyplněn'}, help_text='Zadejte popis značky', verbose_name='Popis značky'),
        ),
        migrations.AlterField(
            model_name='znacka',
            name='rok_zalozeni',
            field=models.PositiveIntegerField(error_messages={'blank': 'Rok založení značky musí být vyplněn'}, help_text='Zadejte rok založení značky (1500-2100)', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)], verbose_name='Rok založení'),
        ),
        migrations.AlterField(
            model_name='znacka',
            name='zakladatel',
            field=models.ForeignKey(default=1, error_messages={'blank': 'Zakladatel značky musí být vybrán'}, help_text='Vyberte zakladatele značky', on_delete=django.db.models.deletion.CASCADE, related_name='znacky', to='auta.zakladatel', verbose_name='Zakladatel'),
        ),
    ]
