# Generated by Django 5.2.1 on 2025-05-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0015_alter_znacka_logo_alter_znacka_popis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakladatel',
            name='biografie',
            field=models.TextField(error_messages={'blank': 'Životopis zakladatele musí být vyplněn'}, help_text='Zadejte životopis zakladatele', verbose_name='Životopis'),
        ),
        migrations.AlterField(
            model_name='zakladatel',
            name='fotografie',
            field=models.ImageField(error_messages={'blank': 'Fotografie zakladatele musí být vybrána'}, help_text='Vyberte fotografii zakladatele', upload_to='zakladatele/', verbose_name='Fotografie autora'),
        ),
        migrations.AlterField(
            model_name='zakladatel',
            name='znacka',
            field=models.ForeignKey(default=1, error_messages={'blank': 'Značka musí být vybrána'}, help_text='Vyberte značku', on_delete=django.db.models.deletion.CASCADE, related_name='zakladatele', to='auta.znacka', verbose_name='Značka'),
        ),
    ]
