# Generated by Django 5.2.1 on 2025-05-20 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0016_alter_zakladatel_biografie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druh',
            name='popis',
            field=models.TextField(error_messages={'blank': 'Popis modelu musí být vyplněn'}, help_text='Zadejte popis modelu', verbose_name='Popis modelu'),
        ),
        migrations.AlterField(
            model_name='druh',
            name='rok_zalozeni',
            field=models.PositiveIntegerField(error_messages={'blank': 'Rok založení modelu musí být vyplněn'}, help_text='Zadejte rok vzniku modelu (1500-2100)', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)], verbose_name='Rok založení'),
        ),
    ]
