# Generated by Django 5.2.1 on 2025-05-20 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0018_alter_znacka_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znacka',
            name='zakladatel',
            field=models.ForeignKey(default=1, error_messages={'blank': 'Zakladatel značky musí být vybrán'}, help_text='Vyberte zakladatele značky', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='znacky', to='auta.zakladatel', verbose_name='Zakladatel'),
        ),
    ]
