# Generated by Django 5.2.1 on 2025-05-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0020_alter_znacka_zakladatel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znacka',
            name='zakladatel',
            field=models.CharField(blank=True, default='Neuvedeno', error_messages={'blank': 'Zakladatel značky musí být vyplněn'}, help_text='Napište jméno a příjmení zakladatele značky', max_length=60, null=True, verbose_name='Zakladatel'),
        ),
    ]
